### ISSUE TITLE
新手求教。。。

### ISSUE THREAD

**Issue by WellSay1** [LooEv/Hello-Blog-by-Django#1]
你好，请问怎么启用多说评论功能呢？可以讲解一下吗，折腾好久了

**Comment by LooEv** [comment]
抱歉，现在才看到这个问题，在Hello-Blog-by-Django/blob/master/djangoloo/settings.py文件的最后面配置多说评论。可惜的是，现在已经没有好用的免费的评论系统给我们使用了，淡淡忧伤

**Comment by LooEv** [comment]
@WellSay1 抱歉，现在才看到这个问题，在Hello-Blog-by-Django/blob/master/djangoloo/settings.py文件的最后面配置多说评论。可惜的是，现在已经没有好用的免费的评论系统给我们使用了，淡淡忧伤
